default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: therapist_matching_development

test:
  <<: *default
  database: therapist_matching_test

production:
  <<: *default
  database: therapist_matching_production
  username: therapist_matching
  password: <%= ENV['THERAPIST_MATCHING_DATABASE_PASSWORD'] %>
